---
galaxy_info:
  author: Roman Kuzmitskii <damex.pp@icloud.com>
  description: cloudflare acme role
  license: GPLv2
  min_ansible_version: 2.12.0
  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - focal
dependencies: []
